---
    name: Run Python Script Daily
    on:
      schedule:
        - cron: 0 0 * * *
      workflow_dispatch:   
    jobs:
      run-python-script:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.9
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          # Step to install Chrome and ChromeDriver
          - name: Install Chrome dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y wget curl unzip

          - name: Install Chrome
            run: |
              wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              sudo apt install ./google-chrome-stable_current_amd64.deb

          - name: Install ChromeDriver
            run: |
              CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
              wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              chmod +x chromedriver
              sudo mv chromedriver /usr/local/bin/  
          - name: Check if secrets are available
            run: |
              echo "MY_EMAIL is set"
              echo "MY_PASSWORD is set"    
          - name: Run the Script
            env:
              MY_EMAIL: ${{ secrets.MY_EMAIL }}
              MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
            run: python main.py
    